# Name: Het Bharatkumar Patel
# SID: 1742431
# CCID: hetbhara
# AnonID: 1000348298
# CMPUT 275, Winter 2023

# Assignment #1 Part 2: Navigation System
# -------------------------------------------

run:
	gnome-terminal -- ./server/server 
	python3 client/client.py

clean:
	cd server && make clean
	rm inpipe outpipe